# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexandrequintart/soft/jsbsim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexandrequintart/soft/jsbsim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"devel\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/Applications/CMake.app/Contents/bin/cpack --config ./CPackSourceConfig.cmake /Users/alexandrequintart/soft/jsbsim/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/Applications/CMake.app/Contents/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandrequintart/soft/jsbsim/CMakeFiles /Users/alexandrequintart/soft/jsbsim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandrequintart/soft/jsbsim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named JSBSim

# Build rule for target.
JSBSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JSBSim
.PHONY : JSBSim

# fast build rule for target.
JSBSim/fast:
	$(MAKE) -f src/CMakeFiles/JSBSim.dir/build.make src/CMakeFiles/JSBSim.dir/build
.PHONY : JSBSim/fast

#=============================================================================
# Target rules for targets named libJSBSim

# Build rule for target.
libJSBSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libJSBSim
.PHONY : libJSBSim

# fast build rule for target.
libJSBSim/fast:
	$(MAKE) -f src/CMakeFiles/libJSBSim.dir/build.make src/CMakeFiles/libJSBSim.dir/build
.PHONY : libJSBSim/fast

#=============================================================================
# Target rules for targets named Init

# Build rule for target.
Init: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Init
.PHONY : Init

# fast build rule for target.
Init/fast:
	$(MAKE) -f src/initialization/CMakeFiles/Init.dir/build.make src/initialization/CMakeFiles/Init.dir/build
.PHONY : Init/fast

#=============================================================================
# Target rules for targets named InputOutput

# Build rule for target.
InputOutput: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 InputOutput
.PHONY : InputOutput

# fast build rule for target.
InputOutput/fast:
	$(MAKE) -f src/input_output/CMakeFiles/InputOutput.dir/build.make src/input_output/CMakeFiles/InputOutput.dir/build
.PHONY : InputOutput/fast

#=============================================================================
# Target rules for targets named Math

# Build rule for target.
Math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Math
.PHONY : Math

# fast build rule for target.
Math/fast:
	$(MAKE) -f src/math/CMakeFiles/Math.dir/build.make src/math/CMakeFiles/Math.dir/build
.PHONY : Math/fast

#=============================================================================
# Target rules for targets named Models

# Build rule for target.
Models: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Models
.PHONY : Models

# fast build rule for target.
Models/fast:
	$(MAKE) -f src/models/CMakeFiles/Models.dir/build.make src/models/CMakeFiles/Models.dir/build
.PHONY : Models/fast

#=============================================================================
# Target rules for targets named Atmosphere

# Build rule for target.
Atmosphere: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Atmosphere
.PHONY : Atmosphere

# fast build rule for target.
Atmosphere/fast:
	$(MAKE) -f src/models/atmosphere/CMakeFiles/Atmosphere.dir/build.make src/models/atmosphere/CMakeFiles/Atmosphere.dir/build
.PHONY : Atmosphere/fast

#=============================================================================
# Target rules for targets named Propulsion

# Build rule for target.
Propulsion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Propulsion
.PHONY : Propulsion

# fast build rule for target.
Propulsion/fast:
	$(MAKE) -f src/models/propulsion/CMakeFiles/Propulsion.dir/build.make src/models/propulsion/CMakeFiles/Propulsion.dir/build
.PHONY : Propulsion/fast

#=============================================================================
# Target rules for targets named FlightControl

# Build rule for target.
FlightControl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlightControl
.PHONY : FlightControl

# fast build rule for target.
FlightControl/fast:
	$(MAKE) -f src/models/flight_control/CMakeFiles/FlightControl.dir/build.make src/models/flight_control/CMakeFiles/FlightControl.dir/build
.PHONY : FlightControl/fast

#=============================================================================
# Target rules for targets named Simgear

# Build rule for target.
Simgear: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Simgear
.PHONY : Simgear

# fast build rule for target.
Simgear/fast:
	$(MAKE) -f src/simgear/CMakeFiles/Simgear.dir/build.make src/simgear/CMakeFiles/Simgear.dir/build
.PHONY : Simgear/fast

#=============================================================================
# Target rules for targets named Structure

# Build rule for target.
Structure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Structure
.PHONY : Structure

# fast build rule for target.
Structure/fast:
	$(MAKE) -f src/simgear/structure/CMakeFiles/Structure.dir/build.make src/simgear/structure/CMakeFiles/Structure.dir/build
.PHONY : Structure/fast

#=============================================================================
# Target rules for targets named Properties

# Build rule for target.
Properties: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Properties
.PHONY : Properties

# fast build rule for target.
Properties/fast:
	$(MAKE) -f src/simgear/props/CMakeFiles/Properties.dir/build.make src/simgear/props/CMakeFiles/Properties.dir/build
.PHONY : Properties/fast

#=============================================================================
# Target rules for targets named Magvar

# Build rule for target.
Magvar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Magvar
.PHONY : Magvar

# fast build rule for target.
Magvar/fast:
	$(MAKE) -f src/simgear/magvar/CMakeFiles/Magvar.dir/build.make src/simgear/magvar/CMakeFiles/Magvar.dir/build
.PHONY : Magvar/fast

#=============================================================================
# Target rules for targets named Misc

# Build rule for target.
Misc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Misc
.PHONY : Misc

# fast build rule for target.
Misc/fast:
	$(MAKE) -f src/simgear/misc/CMakeFiles/Misc.dir/build.make src/simgear/misc/CMakeFiles/Misc.dir/build
.PHONY : Misc/fast

#=============================================================================
# Target rules for targets named Xml

# Build rule for target.
Xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Xml
.PHONY : Xml

# fast build rule for target.
Xml/fast:
	$(MAKE) -f src/simgear/xml/CMakeFiles/Xml.dir/build.make src/simgear/xml/CMakeFiles/Xml.dir/build
.PHONY : Xml/fast

#=============================================================================
# Target rules for targets named IOStreams

# Build rule for target.
IOStreams: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IOStreams
.PHONY : IOStreams

# fast build rule for target.
IOStreams/fast:
	$(MAKE) -f src/simgear/io/iostreams/CMakeFiles/IOStreams.dir/build.make src/simgear/io/iostreams/CMakeFiles/IOStreams.dir/build
.PHONY : IOStreams/fast

#=============================================================================
# Target rules for targets named PythonJSBSim

# Build rule for target.
PythonJSBSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PythonJSBSim
.PHONY : PythonJSBSim

# fast build rule for target.
PythonJSBSim/fast:
	$(MAKE) -f python/CMakeFiles/PythonJSBSim.dir/build.make python/CMakeFiles/PythonJSBSim.dir/build
.PHONY : PythonJSBSim/fast

#=============================================================================
# Target rules for targets named FGLocationTest1

# Build rule for target.
FGLocationTest1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FGLocationTest1
.PHONY : FGLocationTest1

# fast build rule for target.
FGLocationTest1/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/FGLocationTest1.dir/build.make tests/unit_tests/CMakeFiles/FGLocationTest1.dir/build
.PHONY : FGLocationTest1/fast

#=============================================================================
# Target rules for targets named FGQuaternionTest1

# Build rule for target.
FGQuaternionTest1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FGQuaternionTest1
.PHONY : FGQuaternionTest1

# fast build rule for target.
FGQuaternionTest1/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/FGQuaternionTest1.dir/build.make tests/unit_tests/CMakeFiles/FGQuaternionTest1.dir/build
.PHONY : FGQuaternionTest1/fast

#=============================================================================
# Target rules for targets named FGMatrix33Test1

# Build rule for target.
FGMatrix33Test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FGMatrix33Test1
.PHONY : FGMatrix33Test1

# fast build rule for target.
FGMatrix33Test1/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/FGMatrix33Test1.dir/build.make tests/unit_tests/CMakeFiles/FGMatrix33Test1.dir/build
.PHONY : FGMatrix33Test1/fast

#=============================================================================
# Target rules for targets named FGJSBBaseTest1

# Build rule for target.
FGJSBBaseTest1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FGJSBBaseTest1
.PHONY : FGJSBBaseTest1

# fast build rule for target.
FGJSBBaseTest1/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/FGJSBBaseTest1.dir/build.make tests/unit_tests/CMakeFiles/FGJSBBaseTest1.dir/build
.PHONY : FGJSBBaseTest1/fast

#=============================================================================
# Target rules for targets named StringUtilitiesTest1

# Build rule for target.
StringUtilitiesTest1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StringUtilitiesTest1
.PHONY : StringUtilitiesTest1

# fast build rule for target.
StringUtilitiesTest1/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/StringUtilitiesTest1.dir/build.make tests/unit_tests/CMakeFiles/StringUtilitiesTest1.dir/build
.PHONY : StringUtilitiesTest1/fast

#=============================================================================
# Target rules for targets named FGColumnVector3Test1

# Build rule for target.
FGColumnVector3Test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FGColumnVector3Test1
.PHONY : FGColumnVector3Test1

# fast build rule for target.
FGColumnVector3Test1/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/FGColumnVector3Test1.dir/build.make tests/unit_tests/CMakeFiles/FGColumnVector3Test1.dir/build
.PHONY : FGColumnVector3Test1/fast

#=============================================================================
# Target rules for targets named aeromatic

# Build rule for target.
aeromatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aeromatic
.PHONY : aeromatic

# fast build rule for target.
aeromatic/fast:
	$(MAKE) -f utils/aeromatic++/CMakeFiles/aeromatic.dir/build.make utils/aeromatic++/CMakeFiles/aeromatic.dir/build
.PHONY : aeromatic/fast

#=============================================================================
# Target rules for targets named Aeromatic++

# Build rule for target.
Aeromatic++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Aeromatic++
.PHONY : Aeromatic++

# fast build rule for target.
Aeromatic++/fast:
	$(MAKE) -f utils/aeromatic++/CMakeFiles/Aeromatic++.dir/build.make utils/aeromatic++/CMakeFiles/Aeromatic++.dir/build
.PHONY : Aeromatic++/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... doc"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... dist"
	@echo "... JSBSim"
	@echo "... libJSBSim"
	@echo "... Init"
	@echo "... InputOutput"
	@echo "... Math"
	@echo "... Models"
	@echo "... Atmosphere"
	@echo "... Propulsion"
	@echo "... FlightControl"
	@echo "... Simgear"
	@echo "... Structure"
	@echo "... Properties"
	@echo "... Magvar"
	@echo "... Misc"
	@echo "... Xml"
	@echo "... IOStreams"
	@echo "... PythonJSBSim"
	@echo "... FGLocationTest1"
	@echo "... FGQuaternionTest1"
	@echo "... FGMatrix33Test1"
	@echo "... FGJSBBaseTest1"
	@echo "... StringUtilitiesTest1"
	@echo "... FGColumnVector3Test1"
	@echo "... aeromatic"
	@echo "... Aeromatic++"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

